#![allow(clippy::exhaustive_enums, reason = "Generated by sol! macro")]
#![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]

use alloy::primitives::U256;
use alloy::sol;
use anyhow::{Context, Result};
use clap::{Args, Subcommand};
use futures::FutureExt;
use polymarket_client_sdk_v2::types::{Address, address};
use polymarket_client_sdk_v2::{POLYGON, contract_config};

use crate::auth;
use crate::output::OutputFormat;
use crate::output::approve::{ApprovalStatus, print_approval_status, print_tx_result};

/// Polygon pUSD (same address as `PUSD_ADDRESS_STR`; `address!` requires a literal).
const PUSD_ADDRESS: Address = address!("0xC011a7E12a19f7B1f670d46F03B03f3342E82DFB");

sol! {
    #[sol(rpc)]
    interface IERC20 {
        function approve(address spender, uint256 value) external returns (bool);
        function allowance(address owner, address spender) external view returns (uint256);
    }

    #[sol(rpc)]
    interface IERC1155 {
        function setApprovalForAll(address operator, bool approved) external;
        function isApprovedForAll(address account, address operator) external view returns (bool);
    }
}

#[derive(Args)]
pub struct ApproveArgs {
    #[command(subcommand)]
    pub command: ApproveCommand,
}

#[derive(Subcommand)]
pub enum ApproveCommand {
    /// Check current contract approvals for a wallet
    Check {
        /// Wallet address to check (defaults to configured wallet)
        address: Option<Address>,
    },
    /// Approve all required contracts for trading (sends on-chain transactions)
    Set,
}

struct ApprovalTarget {
    name: &'static str,
    address: Address,
}

fn approval_targets() -> Result<Vec<ApprovalTarget>> {
    let config = contract_config(POLYGON, false).context("No contract config for Polygon")?;
    let neg_risk_config =
        contract_config(POLYGON, true).context("No neg-risk contract config for Polygon")?;

    let mut targets = vec![
        ApprovalTarget {
            name: "CTF Exchange (v1)",
            address: config.exchange,
        },
        ApprovalTarget {
            name: "Neg Risk Exchange (v1)",
            address: neg_risk_config.exchange,
        },
    ];

    if let Some(exchange_v2) = config.exchange_v2 {
        targets.push(ApprovalTarget {
            name: "CTF Exchange (v2)",
            address: exchange_v2,
        });
    }

    if let Some(exchange_v2) = neg_risk_config.exchange_v2 {
        targets.push(ApprovalTarget {
            name: "Neg Risk Exchange (v2)",
            address: exchange_v2,
        });
    }

    if let Some(adapter) = neg_risk_config.neg_risk_adapter {
        targets.push(ApprovalTarget {
            name: "Neg Risk Adapter",
            address: adapter,
        });
    }

    Ok(targets)
}

pub async fn execute(
    args: ApproveArgs,
    output: OutputFormat,
    private_key: Option<&str>,
) -> Result<()> {
    match args.command {
        ApproveCommand::Check { address } => check(address, private_key, output).await,
        ApproveCommand::Set => set(private_key, output).await,
    }
}

async fn check(
    address_arg: Option<Address>,
    private_key: Option<&str>,
    output: OutputFormat,
) -> Result<()> {
    let owner: Address = if let Some(addr) = address_arg {
        addr
    } else {
        let signer = auth::resolve_signer(private_key)?;
        polymarket_client_sdk_v2::auth::Signer::address(&signer)
    };

    let provider = auth::create_readonly_provider().await?;
    let config = contract_config(POLYGON, false).context("No contract config for Polygon")?;

    let pusd = IERC20::new(PUSD_ADDRESS, provider.clone());
    let ctf = IERC1155::new(config.conditional_tokens, provider.clone());

    let targets = approval_targets()?;
    let mut statuses = Vec::new();

    for target in &targets {
        let (pusd_allowance, pusd_error) = match pusd.allowance(owner, target.address).call().await
        {
            Ok(val) => (val, None),
            Err(e) => (U256::ZERO, Some(e.to_string())),
        };

        let (ctf_approved, ctf_error) =
            match ctf.isApprovedForAll(owner, target.address).call().await {
                Ok(val) => (val, None),
                Err(e) => (false, Some(e.to_string())),
            };

        statuses.push(ApprovalStatus {
            contract_name: target.name.to_string(),
            contract_address: format!("{}", target.address),
            pusd_allowance,
            ctf_approved,
            pusd_error,
            ctf_error,
        });
    }

    print_approval_status(&statuses, &output)
}

async fn set(private_key: Option<&str>, output: OutputFormat) -> Result<()> {
    use futures::stream::{FuturesUnordered, StreamExt};

    let provider = auth::create_provider(private_key).await?;
    let config = contract_config(POLYGON, false).context("No contract config for Polygon")?;

    let pusd = IERC20::new(PUSD_ADDRESS, provider.clone());
    let ctf = IERC1155::new(config.conditional_tokens, provider.clone());

    let targets = approval_targets()?;
    let total = targets.len() * 2;

    if matches!(output, OutputFormat::Table) {
        println!("Approving {total} contracts in parallel...\n");
    }

    // Build the full task set up front. Each task = (step_label, kind, contract_name, future).
    // alloy's default ProviderBuilder includes a NonceFiller that allocates distinct nonces
    // atomically per request, so concurrent sends from the same EOA are safe.
    let mut tasks: FuturesUnordered<_> = FuturesUnordered::new();
    let mut step_idx: usize = 0;

    for target in &targets {
        step_idx += 1;
        let label = format!("pUSD \u{2192} {}", target.name);
        let kind = "erc20";
        let contract_name = target.name.to_string();
        let pusd = pusd.clone();
        let target_addr = target.address;
        let target_name_for_err = target.name;
        let step = step_idx;
        tasks.push(
            async move {
                let tx_hash = pusd
                    .approve(target_addr, U256::MAX)
                    .send()
                    .await
                    .context(format!(
                        "Failed to send pUSD approval for {target_name_for_err}"
                    ))?
                    .watch()
                    .await
                    .context(format!(
                        "Failed to confirm pUSD approval for {target_name_for_err}"
                    ))?;
                Ok::<_, anyhow::Error>((step, label, kind, contract_name, tx_hash))
            }
            .boxed(),
        );

        step_idx += 1;
        let label = format!("CTF  \u{2192} {}", target.name);
        let kind = "erc1155";
        let contract_name = target.name.to_string();
        let ctf = ctf.clone();
        let target_addr = target.address;
        let target_name_for_err = target.name;
        let step = step_idx;
        tasks.push(
            async move {
                let tx_hash = ctf
                    .setApprovalForAll(target_addr, true)
                    .send()
                    .await
                    .context(format!(
                        "Failed to send CTF approval for {target_name_for_err}"
                    ))?
                    .watch()
                    .await
                    .context(format!(
                        "Failed to confirm CTF approval for {target_name_for_err}"
                    ))?;
                Ok::<_, anyhow::Error>((step, label, kind, contract_name, tx_hash))
            }
            .boxed(),
        );
    }

    let mut completed = 0usize;
    let mut json_results: Vec<serde_json::Value> = Vec::with_capacity(total);
    let mut first_error: Option<anyhow::Error> = None;

    while let Some(res) = tasks.next().await {
        match res {
            Ok((step, label, kind, contract_name, tx_hash)) => {
                completed += 1;
                match output {
                    OutputFormat::Table => {
                        // Step number reflects the original launch order, not completion order;
                        // the suffix after `total` tells the user how many of N have landed.
                        print_tx_result(step, total, &label, tx_hash);
                    }
                    OutputFormat::Json => {
                        json_results.push(serde_json::json!({
                            "step": step,
                            "type": kind,
                            "contract": contract_name,
                            "tx_hash": format!("{tx_hash}"),
                        }));
                    }
                }
            }
            Err(e) => {
                if matches!(output, OutputFormat::Table) {
                    eprintln!("[error] {e:#}");
                }
                if first_error.is_none() {
                    first_error = Some(e);
                }
            }
        }
    }

    if let Some(err) = first_error {
        return Err(err);
    }

    match output {
        OutputFormat::Table => {
            println!("\nAll {completed} approval transactions confirmed. You're ready to trade.");
        }
        OutputFormat::Json => {
            // Render in original launch order so output is deterministic across runs.
            json_results.sort_by_key(|v| v.get("step").and_then(|s| s.as_u64()).unwrap_or(0));
            println!("{}", serde_json::to_string_pretty(&json_results)?);
        }
    }

    Ok(())
}
